# Generated by Django 3.2.3 on 2021-06-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='album',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
