# Generated by Django 3.2.3 on 2021-06-16 09:25

from django.db import migrations, models
import django.utils.timezone
import datetime
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210612_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='practice',
            name='end',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='start',
        ),
        migrations.AddField(
            model_name='practice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(hours=10)),
            preserve_default=False,
        ),
    ]
