# Generated by Django 3.2.3 on 2021-06-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210619_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='base.instrument'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='base.piece'),
        ),
    ]
