# Generated by Django 3.2.3 on 2021-06-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210619_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='comments',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='instrument',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
